var data = {
    "fr": {
        "project": "Projets",
        "education" : "Formation",
        "about" : "À propos",
        "contact" : "Contact",
        "heroTitle": `PHOMASONE<br><span class="accent">DOAN KEVIN</span>`,
        "subtitle": "Étudiant en 2e année · BUT Informatique",
        "view_project" : "Voir mes projets",
        "cv_download" : "Télécharger CV",
        "teaser-item-descFLIP7" : "Jeu de cartes en équipe, architecture MVC, scoreboard dynamique et graphiques de score.",
        "teaser-item-descMARIO" : "Jeu style Mario Maker, réalisé en équipe. Musique originale composée par mes soins.",
        "teaser-item-titleRESEAU" : "Analyse de réseau social",
        "teaser-item-descRESEAU" : "Graphe non orienté, Dijkstra, Bellman-Ford et visualisation des communautés.",
        "teaser-view-all-btn" : "Voir tous les projets",
        "formation-item-titleBUT" : "BUT Informatique",
        "formation-item-descBUT" : "Formation universitaire technologique en informatique. Programmation, algorithmes, mathématiques, bases de données, réseaux, gestion de projet et développement web.",
        "formation-item-titleBAC" : "Baccalauréat",
        "formation-item-place" :"Lycée Joliot Curie-Rennes",
        "formation-item-descBAC" : "Spécialités Numérique et Sciences Informatiques (NSI) et Mathématiques. Première expérience de la programmation, algorithmique et bases de données.",
        "xp-section-title" : "Compétences",
        "xp-skill-card-titleL" : "Langages",
        "xp-skill-card-titleB" : "Bases de données",
        "xp-skill-card-titleO" : "Outils",
        "row" : "© 2026 Phomasone Doan Kevin - Tous droits réservés",
        "about-hero-title": "À propos de <em>Moi</em>",
        "about-hero-desc": `Bonjour, je m'appelle Phomasone Doan Kevin.<br><br>
            Je suis né le 13/08/2007 à Ho-Chi-Minh-Ville, au Vietnam. J'ai grandi là-bas et j'ai fait 
            toute ma scolarité au lycée français international Marguerite Duras. En 2022, j'ai déménagé 
            en France pour continuer mes études, j'y ai fait mon lycée puis mes études supérieures.<br><br>
            C'est en Première, grâce à la spécialité NSI, que j'ai commencé à coder. Je n'avais jamais 
            touché à ça avant, donc les débuts n'ont pas été évidents. J'ai persévéré, et au Bac j'ai fini 
            avec 20/20 en maths et 18/20. J'en étais vraiment fier.<br><br>
            Après le Bac, j'ai voulu continuer sur cette voie et j'ai intégré un BUT Informatique à l'IUT de Nantes. Cette 
            formation m'a permis d'aller plus loin dans le développement logiciel et d'apprendre à gérer de 
            vrais projets techniques, en équipe comme en solo. Après ça, j'aimerais intégrer une école 
            d'ingénieur et devenir ingénieur logiciel, ingénieur IA, ou encore ingénieur machine learning, 
            je suis encore en train d'affiner ce choix.`,
        "contact-title" : "Contacter <span>Moi</span>",
        "form-labelNom" : "Nom",
        "form-labelMail" : "Adresse Mail",
        "form-labelMessage" : "Message",
        "contact-message-placeholder": "Votre message ici...",
        "send_message" : "Envoyer le message",
        "card-title1" : "Portfolio Personnel",
        "card-title2" : "Systeme de Particule",
        "card-title3" : "Mario Maker",
        "card-title4" : "Web Html",
        "card-title5" : "Flip 7",
        "card-desc1" : "Site web Porfolio développé en BUT Informatique.",
        "card-desc2" : "Projet Golang en 1ère Annee BUT INFO. Développement d'un moteur de simulation 2D en utilisant Ebitengine",
        "card-desc3" : "Projet fin d'anneé developé en Terminal avec 4 personne",
        "card-desc4" : "Sites Web développés avec HTML/CSS/JAVASCRIPT",
        "card-desc5" : "Développement d'une jeu - Flip7",
        "card-desc6" : "Visualisation des réseaux sociaux",
        "back-link" : "Retour aux projets",
        "hero-titleParticule" : `<span style="color: #fc8888;">Système de</span><br><span>Particules</span>`,
        "hero-descParticule" : "Simulation 2D d'un système de particules développé en Go avec la bibliothèque Ebitengine. Le projet gère la gravité, les collisions, les formes de générateur, les variations de couleur et bien plus encore.",
        "github": "Voir sur Github",
        "hero-titleMario" : `<span style="color: #88ddfc";>Jeu de Plateforme</span><br><span>Mario Maker</span>`,
        "hero-descMario" :"Un jeu de plateforme inspiré de Super Mario Maker, développé en Python avec Pygame en première année. Éditeur de niveaux complet, deux types d'ennemis avec IA, système d'objets, musique originale composée par moi, et support manette Xbox 360.",
        "hero-titleWeb" : "Mes Sites<br><span>Web</span>",
        "hero-descWeb" : "Petites sites web développées en HTML, CSS et JavaScript. Clique sur une carte pour voir le site en direct",
        "card-link" : "Ouvrir",
        "mini-card-name1" :"Site Web de Montre",
        "mini-card-desc1" : "Projet de Site marchandise - Apprentissage du css",
        "mini-card-name2" :"IMC Calculator",
        "mini-card-desc2" : "Calcul de l'indice de masse corporelle en fonction du poids et de la taille.",
        "mini-card-name3" :"Calculatrice",
        "mini-card-desc3" : "Calculatrice simple avec les opérations de base : addition, soustraction, multiplication, division.",
        "mini-card-name4" :"Convertisseur de Température",
        "card-desc4" : "Conversion des températures entre Celsius, Fahrenheit et Kelvin en temps réel.",
        "hero-titleFlip7" : "Jeu de Cartes<br><span>Flip7</span>",
        "hero-descFlip7" : "Un jeu de cartes Flip7 développée en Kotlin avec JavaFX. Architecture MVC stricte, système de scoreboard avec historique des manches, visualisation des scores en graphique, affichage du podium en fin de partie.",
        "hero-titleReseaux" : "<span>Analyse de</span><br>Réseau Social",
        "hero-descReseaux" : "Analyse des graphe de réseaux sociaux (Deezer-Git-Twitch) développée en Python. Le projet gère la détection et le filtrage des nœuds isolés, l'application de dégradés de couleur selon le degré et la proximité, ainsi qu'un algorithme de Dijkstra optimisé sur la plus grande composante connexe.",
    },
    "en": {
        "project": "Projects",
        "education" : "Education",
        "about" : "About",
        "contact" : "Contact",
        "heroTitle": `PHOMASONE<br><span class="accent">DOAN KEVIN</span>`,
        "subtitle": "Second-year student · BSc in Computer Science",
        "view_project" : "View Projects",
        "cv_download" : "Download CV",
        "teaser-item-descFLIP7" : "Team-based card game, MVC architecture, dynamic scoreboard and score charts.",
        "teaser-item-descMARIO" : "A Mario Maker-style game, developed as a team. Original music composed by me.",
        "teaser-item-titleRESEAU" : "Social Network Analysis",
        "teaser-item-descRESEAU" : "Undirected graphs, Dijkstra, Bellman-Ford, and community visualization.",
        "teaser-view-all-btn" : "View All Projects",
        "formation-item-titleBUT" : "BSc in Computer Science",
        "formation-item-descBUT" : "University-level technical training in computer science. Programming, algorithms, mathematics, databases, networks, project management, and web development.",
        "formation-item-titleBAC" : "High School Diploma",
        "formation-item-place" :"Joliot-Curie High School, Rennes",
        "formation-item-descBAC" : "Specializations in Digital Sciences and Computer Science (NSI) and Mathematics. Initial experience with programming, algorithms, and databases.",
        "xp-section-title" : "Skills",
        "xp-skill-card-titleL" : "Languages",
        "xp-skill-card-titleB" : "Data Base",
        "xp-skill-card-titleO" : "Tools",
        "row" : "© 2026 Phomasone Doan Kevin - All rights reserved",
        "about-hero-title": "About <em>Me</em>",
        "about-hero-desc": `Hello, my name is Phomasone Doan Kevin.<br><br>
            I was born on August 13, 2007, in Ho Chi Minh City, Vietnam. I grew up there and attended
            the Marguerite Duras International French High School throughout my entire schooling. In 2022, I moved
            to France to continue my studies; I attended high school there and then went on to college.<br><br>
            It was in my 11th grade, thanks to the Digital Sciences and Computer Science track, that I started coding. I had never
            done anything like that before, so the beginning wasn’t easy. I carried on, and on my Hight School Leaving exam, I scored
            20/20 in math and 18/20 in computer science. I was really proud of that.<br><br>
            After that, I wanted to continue on this path and enrolled in a Bachelor’s Degree in Computer Science at the IUT of Nantes. This
            program allowed me to dig deeper into software development and learn how to manage
            real technical projects, both as part of a team and on my own. After that, I’d like to attend an
            engineering school and become a software engineer, an AI engineer, or even a machine learning engineer,
            I’m still refining that decision.`,
        "contact-title" : "Contact <span>Me</span>",
        "form-labelNom" : "Name",
        "form-labelMail" : "Email Adress",
        "form-labelMessage" : "Message",
        "contact-message-placeholder": "Your message here...",
        "send_message" : "Send Message",
        "card-title1" : "Personal Portfolio",
        "card-title2" : "Particle System",
        "card-title3" : "Mario Maker",
        "card-title4" : "Web HTML",
        "card-title5" : "Flip 7",
        "card-desc1" : "Showcase Portfolio website developed throughout my Bachelor's Degree.",
        "card-desc2" : "Golang project as a freshman. Development of a 2D simulation engine using Ebitengine",
        "card-desc3" : "End-of-year project developed in 12th grade with a team of 4 people",
        "card-desc4" : "Websites developed using HTML/CSS/JavaScript",
        "card-desc5" : "Development of a game - Flip7",
        "card-desc6" : "Social Network visualization",
        "back-link" : "Back to Projects",
        "hero-titleParticule" : `<span style="color: #fc8888;">Particle</span><br><span>System</span>`,
        "hero-descParticule" : "A 2D simulation of a particle system developed in Golang using the Ebitengine library. The project handles gravity, collisions, generator shapes, color variations, and much more.",
        "github": "See on Github",
        "hero-titleMario" : `<span style="color: #88ddfc";>Platformer Game</span><br><span>Mario Maker</span>`,
        "hero-descMario" :"A platformer inspired by Super Mario Maker, developed in Python using Pygame during my freshman year. It features a full-featured level editor, two types of enemies with AI, an item system, original music composed by me, and support for the Xbox 360 controller.",
        "hero-titleWeb" : "My<br><span>Websites</span>",
        "hero-descWeb" : "Small websites developed using HTML, CSS, and JavaScript. Click on a map to view the website live",
        "card-link" : "Open",
        "mini-card-name1" : "Watch Website",
        "mini-card-desc1" : "E-commerce Website Project - Learning CSS",
        "mini-card-name2" :"BMI Calculator",
        "mini-card-desc2" : "Calculates body mass index based on weight and height.",
        "mini-card-name3" :"Calculator",
        "mini-card-desc3" : "Simple calculator with basic operations: addition, subtraction, multiplication, and division.",
        "mini-card-name4" :"Temperature Converter",
        "mini-card-desc4" : "Converts temperatures between Celsius, Fahrenheit, and Kelvin in real time.",
        "hero-titleFlip7" : "Card Game<br><span>Flip7</span>",
        "hero-descFlip7" : "Flip7 is a card game developed in Kotlin using JavaFX. It features a strict MVC architecture, a scoreboard system with round history, graphical score displays, and a leaderboard displayed at the end of the game.",
        "hero-titleReseaux" : "<span>Analysis of</span><br>Social Networks",
        "hero-descReseaux" : "Analysis of social network graphs (Deezer, Git, Twitch) developed in Python. The project handles the detection and filtering of isolated nodes, the application of color gradients based on degree and proximity, and a Dijkstra algorithm optimized for the largest connected component.",
    },
    "vi": {
        "project": "Dự án",
        "education" : "Học vấn",
        "about" : "Về Mình",
        "contact" : "Liên hệ",
        "heroTitle": `PHOMASONE<br><span class="accent">ĐOÀN KEVIN</span>`,
        "subtitle": "Sinh viên năm hai · Chuyên ngành Công nghệ Thông tin",
        "view_project" : "Các dự án ",
        "cv_download" : "Tải CV",
        "teaser-item-descFLIP7" : "Trò chơi bài theo đội, kiến trúc MVC, bảng điểm động và biểu đồ điểm số.",
        "teaser-item-descMARIO" : "Một trò chơi theo phong cách Mario Maker, được phát triển bởi cả nhóm. Nhạc nền do chính mình sáng tác.",
        "teaser-item-titleRESEAU" : "Phân tích mạng xã hội",
        "teaser-item-descRESEAU" : "Đồ thị không định hướng, thuật toán Dijkstra, thuật toán Bellman-Ford và trực quan hóa cộng đồng.",
        "teaser-view-all-btn" : "Xem tất cả các dự án",
        "formation-item-titleBUT" : "Cử nhân Khoa học Máy tính",
        "formation-item-descBUT" : "Đào tạo kỹ thuật cấp đại học về khoa học máy tính. Lập trình, thuật toán, toán học, cơ sở dữ liệu, mạng máy tính, quản lý dự án và phát triển web.",
        "formation-item-titleBAC" : "Tốt nghiệp trung học phổ thông", 
        "formation-item-place" :"Trường Trung học Joliot-Curie, Rennes",
        "formation-item-descBAC" : "Chuyên ngành Công nghệ số và Khoa học Máy tính và Toán học. Có kinh nghiệm ban đầu về lập trình, thuật toán và cơ sở dữ liệu.",
        "xp-section-title" : "Kỹ năng",
        "xp-skill-card-titleL" : "Ngôn Ngữ",
        "xp-skill-card-titleB" : "Cơ sở dữ liệu",
        "xp-skill-card-titleO" : "Công cụ",
        "row" : "© 2026 Phomasone Doan Kevin - Mọi quyền được bảo lưu",
        "about-hero-title": "Về <em>Mình</em>",
        "about-hero-desc": `Xin chào, tên mình là Phomasone Đoàn Kevin, tên việt là Đoàn Minh Đức.<br><br>
            Mình sinh ngày 13/08/2007 tại Thành phố Hồ Chí Minh, Việt Nam. Mình lớn lên ở đó và đã theo học
            toàn bộ quãng thời gian học tập tại Trường Trung học Quốc tế Pháp Marguerite Duras. Năm 2022, mình chuyển đến
            Pháp để tiếp tục việc học, tại đó mình đã học trung học phổ thông rồi đại học.<br><br>
            Khi học lớp 11, nhờ chuyên ngành Công nghệ số và Khoa học Máy tính, ình bắt đầu học lập trình. Trước đó mình chưa bao giờ
            tiếp xúc với lĩnh vực này, nên những bước đầu không hề dễ dàng. Mình đã kiên trì, và khi thi tốt nghiệp, mình đã đạt
            20/20 môn Toán và 18/20 môn Khoa học Máy tính. Mình thực sự rất tự hào về điều đó.<br><br>
            Sau khi tốt nghiệp, mình muốn tiếp tục theo đuổi con đường này và đã nhập học chương trình Cử nhân Công nghệ Thông tin tại IUT Nantes. Chương trình
            đào tạo này đã giúp mình đi sâu hơn vào lĩnh vực phát triển phần mềm và học cách quản lý
            các dự án kỹ thuật thực tế, cả khi làm việc theo nhóm lẫn độc lập. Sau này, mình mong muốn theo học tại một trường
            kỹ sư và trở thành kỹ sư phần mềm, kỹ sư trí tuệ nhân tạo (AI) hoặc kỹ sư học máy (machine learning),
            hiện tại mình vẫn đang cân nhắc kỹ lưỡng về lựa chọn này.`,
        "contact-title" : "Liên hệ với <span>Mình</span>",
        "form-labelNom" : "Tên",
        "form-labelMail" : "Địa chỉ email",
        "form-labelMessage" : "Nội dung tin nhắn",
        "contact-message-placeholder": "Nhắn ở đây...",
        "send_message" : "Gửi tin nhắn",
        "card-title1" : "Portfolio cá nhân",
        "card-title2" : "Hệ thống va chạm hạt",
        "card-title3" : "Mario Maker",
        "card-title4" : "Web HTML",
        "card-title5" : "Flip 7",
        "card-desc1" : "Trang web Portfolio được phát triển trong lúc học Cử nhân Công nghệ Thông tin.",
        "card-desc2" : "Dự án Golang trong khi học năm nhất. Phát triển một công cụ mô phỏng 2D bằng cách sử dụng Ebitengine",
        "card-desc3" : "Dự án cuối năm 12 được phát triển cùng với 4 thành viên",
        "card-desc4" : "Các trang web được phát triển bằng HTML/CSS/JAVASCRIPT",
        "card-desc5" : "Phát triển một trò chơi thẻ - Flip7",
        "card-desc6" : "Hiển thị các mạng xã hội",
        "back-link": "Quay lại các dự án",
        "hero-titleParticule" : `<span style="color: #fc8888;">Hệ thống</span><br><span>Hạt</span>`,
        "hero-descParticule" : "Mô phỏng 2D của một hệ thống hạt được phát triển bằng ngôn ngữ Golang với thư viện Ebitengine. Dự án này hỗ trợ các tính năng như trọng lực, va chạm, các kiểu tạo hạt, sự thay đổi màu sắc và nhiều tính năng khác nữa.",
        "github": "xem trên GitHub",
        "hero-titleMario" : `<span style="color: #88ddfc";>Trò chơi đi cảnh</span><br><span>Mario Maker</span>`,
        "hero-descMario" :"Một trò chơi platform lấy cảm hứng từ Super Mario Maker, được phát triển bằng Python kết hợp với Pygame trong năm nhất đại học. Trò chơi có trình chỉnh sửa màn chơi đầy đủ tính năng, hai loại kẻ thù có trí tuệ nhân tạo (AI), hệ thống vật phẩm, nhạc nền gốc do chính Mình sáng tác, và hỗ trợ tay cầm Xbox 360.", 
        "hero-titleWeb" : "Các trang web<br><span>của mình</span>",
        "hero-descWeb" : "Các trang web nhỏ được phát triển bằng HTML, CSS và JavaScript. Nhấp vào để xem trang web trực tiếp",
        "mini-card-name1": "Trang web về đồng hồ",
        "mini-card-desc1": "Dự án trang web bán hàng - Học CSS",
        "mini-card-name2": "Máy tính chỉ số BMI",
        "mini-card-desc2": "Tính chỉ số khối cơ thể dựa trên cân nặng và chiều cao." ,
        "mini-card-name3" :"Máy tính",
        "mini-card-desc3" : "Máy tính đơn giản với các phép tính cơ bản: cộng, trừ, nhân, chia.",
        "mini-card-name4" :"Công cụ chuyển đổi nhiệt độ",
        "mini-card-desc4" : "Chuyển đổi nhiệt độ giữa Celsius, Fahrenheit và Kelvin theo thời gian thực.",
        "hero-titleFlip7" : "Trò chơi bài <br><span>Flip7</span>",
        "hero-descFlip7" : "Flip7 là một trò chơi bài được phát triển bằng Kotlin và JavaFX. Áp dụng kiến trúc MVC nghiêm ngặt, hệ thống bảng điểm có lịch sử các ván đấu, hiển thị điểm số dưới dạng biểu đồ, và hiển thị bảng xếp hạng khi kết thúc ván chơi.",
        "hero-titleReseaux" : "<span>Phân tích</span><br>Mạng xã hội",
        "hero-descReseaux" : "Phân tích đồ thị mạng xã hội (Deezer-Git-Twitch) được phát triển bằng Python. Dự án này thực hiện việc phát hiện và lọc các nút cô lập, áp dụng các sắc thái màu dựa trên độ kết nối và độ gần, cũng như thuật toán Dijkstra được tối ưu hóa trên thành phần liên kết lớn nhất.",
    }
};

var files = {
    "fr": {
        "cv": "assets/cv-fr.pdf"
    },
    "en": {
        "cv": "assets/cv-eng.pdf"
    },
    "vi": {
        "cv": "assets/cv-eng.pdf"
    }
}